name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ windows-2022, ubuntu-22.04 ]
        config: [ config/debug.mk, config/release.mk ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache CMake build folder
        uses: actions/cache@v3
        with:
          path: cmake-build-*/
          key: ${{ runner.os }}-${{ github.job }}-${{ matrix.config }}
      - name: Build and Run unit tests
        run: make test CONFIG=${{ matrix.config }}
      - name: Build and Run integration tests
        run: make it CONFIG=${{ matrix.config }}
  lint:
    name: Lint
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        config: [ config/debug.mk, config/release.mk ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: ${{ matrix.os }}-llvm-16
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "16.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
        # see https://stackoverflow.com/a/51333801/13830772
      - name: Save LLVM and Clang
        uses: actions/cache/save@v3
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Add repo for LLVM 16
        run: |
          wget https://apt.llvm.org/llvm-snapshot.gpg.key
          sudo apt-key add llvm-snapshot.gpg.key
          sudo add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main'
          sudo apt update
      - name: Install chore packages
        run: sudo apt install libncurses5 libc++-16-dev
      - name: Cache CMake build folder
        uses: actions/cache@v3
        with:
          path: cmake-build-*/
          key: ${{ runner.os }}-${{ github.job }}-${{ matrix.config }}
      - name: Lint
        run: make lint CONFIG=${{ matrix.config }}
        env:
          CC: clang
          CXX: clang++
  # see https://github.com/orgs/community/discussions/26822#discussioncomment-5122101
  complete:
    name: Complete CI
    needs: [ test, lint ]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check all job status
        # see https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
        run: exit 1
